namespace PandoraAnalyticsAPI.Domain.Entities
{
    public class LevelPlay
    {
        public int Id { get; set; }

        // Generated by Unity. Prevents duplicate uploads.
        public string EventId { get; set; } = string.Empty;

        // Phone number / player ID
        public string PlayerId { get; set; } = string.Empty;
        public Player Player { get; set; } = null!;

        public string Minigame { get; set; } = string.Empty;
        public int LevelNumber { get; set; }

        public int SuccessfulTrials { get; set; }
        public int RequiredTrials { get; set; }

        public bool NormalPass { get; set; }
        public bool AssistedPass { get; set; }

        public int ActiveDurationMs { get; set; }

        public DateTime StartedAtUtc { get; set; }
        public DateTime CompletedAtUtc { get; set; }
    }
}